<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ITPMO-NB-029754" failures="1" tests="2" name="Training Order Creation - SM_Pulilan" time="332.357" errors="0" timestamp="24 Oct 2022 08:53:53 GMT">
  <testcase classname="com.Shopify.testobjects.TrainingOrderCreationTest" name="openLoginPage" time="89.47">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
	at com.Shopify.testobjects.TrainingOrderCreationTest.openLoginPage(TrainingOrderCreationTest.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- openLoginPage -->
  <testcase classname="com.Shopify.testobjects.TrainingOrderCreationTest" name="createTrainingOrders" time="242.311"/>
</testsuite> <!-- Training Order Creation - SM_Pulilan -->
