<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ITPMO-NB-029754" failures="1" tests="2" name="Training Order Creation - P-BTQ SM BACOOR" time="723.582" errors="0" timestamp="11 Oct 2022 08:04:25 GMT">
  <testcase classname="com.Shopify.testobjects.TrainingOrderCreationTest" name="openLoginPage" time="13.715"/>
  <testcase classname="com.Shopify.testobjects.TrainingOrderCreationTest" name="createTrainingOrders" time="709.289">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
	at com.Shopify.testobjects.TrainingOrderCreationTest.createOrder_BOPIS(TrainingOrderCreationTest.java:469)
	at com.Shopify.testobjects.TrainingOrderCreationTest.createTrainingOrders(TrainingOrderCreationTest.java:212)
	at com.Shopify.testobjects.TrainingOrderCreationTest.createOrder_BOPIS(TrainingOrderCreationTest.java:464)
	at com.Shopify.testobjects.TrainingOrderCreationTest.createTrainingOrders(TrainingOrderCreationTest.java:208)
	at com.Shopify.testobjects.TrainingOrderCreationTest.createOrder_BOPIS(TrainingOrderCreationTest.java:464)
	at com.Shopify.testobjects.TrainingOrderCreationTest.createTrainingOrders(TrainingOrderCreationTest.java:208)
	at com.Shopify.testobjects.TrainingOrderCreationTest.createOrder_BOPIS(TrainingOrderCreationTest.java:464)
	at com.Shopify.testobjects.TrainingOrderCreationTest.createTrainingOrders(TrainingOrderCreationTest.java:188)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- createTrainingOrders -->
</testsuite> <!-- Training Order Creation - P-BTQ SM BACOOR -->
