<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="PC-BSAphoto" failures="1" tests="6" name="Sample" time="118.977" errors="0" timestamp="08 Jun 2022 11:45:56 GMT">
  <testcase classname="com.Sample.testobjects.SampleTest" name="blankEmailOrNumberLogIn" time="17.822"/>
  <testcase classname="com.Sample.testobjects.SampleTest" name="noAccountFound" time="8.997"/>
  <testcase classname="com.Sample.testobjects.SampleTest" name="blankPassword" time="9.72"/>
  <testcase classname="com.Sample.testobjects.SampleTest" name="incorrectPassword" time="10.404"/>
  <testcase classname="com.Sample.testobjects.SampleTest" name="successfulLogIn" time="71.519"/>
  <testcase classname="com.Sample.testobjects.SampleTest" name="logOut" time="0.023">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
	at com.Sample.testobjects.SampleTest.logOut(SampleTest.java:177)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- logOut -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="searchItemWithNoResults" time="0.0">
    <ignored/>
  </testcase> <!-- searchItemWithNoResults -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="openHomePage" time="0.0">
    <ignored/>
  </testcase> <!-- openHomePage -->
  <testcase classname="com.Sample.testobjects.SampleTest" name="searchItemWithResults" time="0.0">
    <ignored/>
  </testcase> <!-- searchItemWithResults -->
</testsuite> <!-- Sample -->
